// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	proto "cs426.yale.edu/lab1/failure_injection/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error)
	GetTrendingVideos(ctx context.Context, in *GetTrendingVideosRequest, opts ...grpc.CallOption) (*GetTrendingVideosResponse, error)
	// Admin API for failure injection
	SetInjectionConfig(ctx context.Context, in *proto.SetInjectionConfigRequest, opts ...grpc.CallOption) (*proto.SetInjectionConfigResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error) {
	out := new(GetVideoResponse)
	err := c.cc.Invoke(ctx, "/video_service.VideoService/GetVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetTrendingVideos(ctx context.Context, in *GetTrendingVideosRequest, opts ...grpc.CallOption) (*GetTrendingVideosResponse, error) {
	out := new(GetTrendingVideosResponse)
	err := c.cc.Invoke(ctx, "/video_service.VideoService/GetTrendingVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetInjectionConfig(ctx context.Context, in *proto.SetInjectionConfigRequest, opts ...grpc.CallOption) (*proto.SetInjectionConfigResponse, error) {
	out := new(proto.SetInjectionConfigResponse)
	err := c.cc.Invoke(ctx, "/video_service.VideoService/SetInjectionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	GetVideo(context.Context, *GetVideoRequest) (*GetVideoResponse, error)
	GetTrendingVideos(context.Context, *GetTrendingVideosRequest) (*GetTrendingVideosResponse, error)
	// Admin API for failure injection
	SetInjectionConfig(context.Context, *proto.SetInjectionConfigRequest) (*proto.SetInjectionConfigResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) GetVideo(context.Context, *GetVideoRequest) (*GetVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideo not implemented")
}
func (UnimplementedVideoServiceServer) GetTrendingVideos(context.Context, *GetTrendingVideosRequest) (*GetTrendingVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendingVideos not implemented")
}
func (UnimplementedVideoServiceServer) SetInjectionConfig(context.Context, *proto.SetInjectionConfigRequest) (*proto.SetInjectionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInjectionConfig not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video_service.VideoService/GetVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetTrendingVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetTrendingVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video_service.VideoService/GetTrendingVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetTrendingVideos(ctx, req.(*GetTrendingVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetInjectionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.SetInjectionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetInjectionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video_service.VideoService/SetInjectionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetInjectionConfig(ctx, req.(*proto.SetInjectionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video_service.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideo",
			Handler:    _VideoService_GetVideo_Handler,
		},
		{
			MethodName: "GetTrendingVideos",
			Handler:    _VideoService_GetTrendingVideos_Handler,
		},
		{
			MethodName: "SetInjectionConfig",
			Handler:    _VideoService_SetInjectionConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video_service/proto/video_service.proto",
}
